apiVersion: v1
kind: Service
metadata:
  name:  shashank-rtp-service
  namespace: shashank
spec:
  type: NodePort
  selector:
    app: shashank-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
